[build-system]
requires = [
  "setuptools>=40.9.0",
  "setuptools-scm",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ["py38"]
include = '\.pyi?$'
